from .AnnounceCommand import AnnounceCommand
from .CoursesCommand import CoursesCommand
from .FacultyCommand import FacultyCommand
from .HelpCommand import HelpCommand
from .IgnoreCommand import IgnoreCommand
from .InfoCommand import InfoCommand
from .NewsCommand import NewsCommand
from .PingCommand import PingCommand
from .ProfessorCommand import ProfessorCommand
from .ShutdownCommand import ShutdownCommand
from .TestCommand import TestCommand
from .EvalCommand import EvalCommand
