from .CoursesCommand import CoursesCommand
from .FacultyCommand import FacultyCommand
from .HelpCommand import HelpCommand
from .InfoCommand import InfoCommand
from .NewsCommand import NewsCommand
from .PingCommand import PingCommand
from .ProfessorCommand import ProfessorCommand
from .TestCommand import TestCommand
from .AnnounceCommand import AnnounceCommand
